#![allow(clippy::redundant_pub_crate)]

use std::collections::{BTreeSet, HashMap};
use std::path::Path;

use super::{
    html_escape_text, json_str_or_empty, json_u64_field, json_usize_field, write_json, write_text,
};

pub(super) fn write_project_graph_view(
    out: &Path,
    graph: &serde_json::Value,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(out)
        .map_err(|e| anyhow::anyhow!("failed to create {}: {e}", out.display()))?;
    write_json(&out.join("graph.json"), graph)?;
    write_text(&out.join("index.html"), &project_graph_view_html(graph))
}

fn project_graph_view_html(graph: &serde_json::Value) -> String {
    let stats = graph.get("stats").unwrap_or(&serde_json::Value::Null);
    let node_count = json_usize_field(stats, "node_count");
    let edge_count = json_usize_field(stats, "edge_count");
    let source_depth = json_usize_field(stats, "max_source_contains_depth");
    let semantic_depth = json_usize_field(stats, "max_semantic_contains_depth");
    let semantic_edges = json_usize_field(stats, "semantic_edge_count");
    let semantic_calls = json_usize_field(stats, "semantic_call_edge_count");
    let nodes = graph
        .get("nodes")
        .and_then(serde_json::Value::as_array)
        .map_or(&[][..], Vec::as_slice);
    let edges = graph
        .get("edges")
        .and_then(serde_json::Value::as_array)
        .map_or(&[][..], Vec::as_slice);
    let semantic_entries = graph
        .pointer("/semantic/origin_map/entries")
        .and_then(serde_json::Value::as_array)
        .map_or(&[][..], Vec::as_slice);
    let node_kinds = nodes
        .iter()
        .filter_map(|node| node.get("kind").and_then(serde_json::Value::as_str))
        .collect::<BTreeSet<_>>();
    let svg = project_graph_view_svg(nodes, edges);
    let mut html = String::new();
    html.push_str("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    html.push_str("<title>ORV Project Graph</title>");
    html.push_str("<style>");
    html.push_str("body{margin:0;background:#f7f7f3;color:#242424;font:14px/1.45 -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}");
    html.push_str("main{max-width:1160px;margin:0 auto;padding:24px}");
    html.push_str("header{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;border-bottom:1px solid #d7d7cf;padding-bottom:14px}");
    html.push_str("h1{font-size:24px;margin:0}p{margin:6px 0 0;color:#555}");
    html.push_str(".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px;margin:18px 0}");
    html.push_str(".stat{border:1px solid #d7d7cf;background:#fff;padding:10px;border-radius:6px}");
    html.push_str(".stat b{display:block;font-size:20px}.graph{overflow:auto;border:1px solid #d7d7cf;background:#fff;border-radius:6px}");
    html.push_str(".filters{display:flex;flex-wrap:wrap;gap:10px;align-items:end;margin:18px 0}.filters label{display:grid;gap:4px;color:#555}.filters input,.filters select{min-width:180px;border:1px solid #d7d7cf;background:#fff;padding:7px;font:inherit}");
    html.push_str("svg{display:block;min-width:900px}.edge{stroke:#b8b8ad;stroke-width:1.4}.node-label{font-size:12px;fill:#242424}.node-kind{font-size:10px;fill:#555}");
    html.push_str("table{width:100%;border-collapse:collapse;margin-top:18px;background:#fff;border:1px solid #d7d7cf}th,td{padding:8px;border-bottom:1px solid #e5e5df;text-align:left}th{font-size:12px;text-transform:uppercase;color:#555}</style>");
    html.push_str("</head><body data-node-count=\"");
    html.push_str(&node_count.to_string());
    html.push_str("\" data-edge-count=\"");
    html.push_str(&edge_count.to_string());
    html.push_str("\"><main><header><div><h1>ORV Project Graph</h1><p>Shared source and semantic graph view generated by <code>orv graph --view</code>.</p></div>");
    html.push_str("<a href=\"graph.json\">graph.json</a></header><section class=\"stats\">");
    for (label, value) in [
        ("Nodes", node_count),
        ("Edges", edge_count),
        ("Source Depth", source_depth),
        ("Semantic Depth", semantic_depth),
        ("Semantic Edges", semantic_edges),
        ("Call Edges", semantic_calls),
    ] {
        html.push_str("<div class=\"stat\"><span>");
        html.push_str(label);
        html.push_str("</span><b>");
        html.push_str(&value.to_string());
        html.push_str("</b></div>");
    }
    html.push_str("</section><section class=\"graph\">");
    html.push_str(&svg);
    html.push_str("</section><section class=\"filters\"><label>Search<input id=\"graph-search\" type=\"search\" autocomplete=\"off\"></label><label>Kind<select id=\"graph-kind-filter\"><option value=\"\">All</option>");
    for kind in node_kinds {
        html.push_str("<option value=\"");
        html.push_str(&html_escape_text(kind));
        html.push_str("\">");
        html.push_str(&html_escape_text(kind));
        html.push_str("</option>");
    }
    html.push_str("</select></label></section><table><thead><tr><th>ID</th><th>Kind</th><th>Name</th><th>File</th></tr></thead><tbody>");
    for node in nodes {
        let kind = json_str_or_empty(node, "kind");
        let name = json_str_or_empty(node, "name");
        html.push_str("<tr data-graph-node-row data-node-kind=\"");
        html.push_str(&html_escape_text(kind));
        html.push_str("\" data-node-name=\"");
        html.push_str(&html_escape_text(name));
        html.push_str("\"><td>");
        html.push_str(&html_escape_text(&json_u64_field(node, "id").to_string()));
        html.push_str("</td><td>");
        html.push_str(&html_escape_text(kind));
        html.push_str("</td><td>");
        html.push_str(&html_escape_text(name));
        html.push_str("</td><td>");
        html.push_str(&html_escape_text(&json_u64_field(node, "file").to_string()));
        html.push_str("</td></tr>");
    }
    html.push_str("</tbody></table><table><thead><tr><th>Origin</th><th>Kind</th><th>Name</th></tr></thead><tbody>");
    for entry in semantic_entries {
        html.push_str("<tr><td>");
        html.push_str(&html_escape_text(json_str_or_empty(entry, "id")));
        html.push_str("</td><td>");
        html.push_str(&html_escape_text(json_str_or_empty(entry, "kind")));
        html.push_str("</td><td>");
        html.push_str(&html_escape_text(json_str_or_empty(entry, "name")));
        html.push_str("</td></tr>");
    }
    html.push_str("</tbody></table><script>function filterProjectGraphRows(){const query=(document.getElementById('graph-search')?.value||'').toLowerCase();const kind=document.getElementById('graph-kind-filter')?.value||'';for(const row of document.querySelectorAll('[data-graph-node-row]')){const matchesKind=!kind||row.dataset.nodeKind===kind;const matchesText=!query||row.textContent.toLowerCase().includes(query);row.hidden=!(matchesKind&&matchesText);}}document.getElementById('graph-search')?.addEventListener('input',filterProjectGraphRows);document.getElementById('graph-kind-filter')?.addEventListener('change',filterProjectGraphRows);filterProjectGraphRows();</script></main></body></html>");
    html
}

pub(super) fn project_graph_view_svg(
    nodes: &[serde_json::Value],
    edges: &[serde_json::Value],
) -> String {
    let row_gap = 54_i64;
    let node_count = i64::try_from(nodes.len()).unwrap_or(i64::MAX / row_gap);
    let height = node_count
        .saturating_mul(row_gap)
        .saturating_add(80)
        .max(220);
    let mut positions: HashMap<u64, (i64, i64)> = HashMap::new();
    for (index, node) in nodes.iter().enumerate() {
        let id = json_u64_field(node, "id");
        let kind = json_str_or_empty(node, "kind");
        let x = project_graph_view_x(kind);
        let row = i64::try_from(index).unwrap_or(i64::MAX / row_gap);
        let y = row.saturating_mul(row_gap).saturating_add(48);
        positions.insert(id, (x, y));
    }
    let mut svg = String::new();
    svg.push_str("<svg role=\"img\" aria-label=\"ORV project graph\" viewBox=\"0 0 920 ");
    svg.push_str(&height.to_string());
    svg.push_str("\" height=\"");
    svg.push_str(&height.to_string());
    svg.push_str("\" xmlns=\"http://www.w3.org/2000/svg\">");
    svg.push_str("<defs><marker id=\"arrow\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"4\" orient=\"auto\"><path d=\"M0,0 L8,4 L0,8 Z\" fill=\"#b8b8ad\"/></marker></defs>");
    for edge in edges {
        let from = json_u64_field(edge, "from");
        let to = json_u64_field(edge, "to");
        let (Some((x1, y1)), Some((x2, y2))) = (positions.get(&from), positions.get(&to)) else {
            continue;
        };
        svg.push_str("<line class=\"edge\" marker-end=\"url(#arrow)\" x1=\"");
        svg.push_str(&x1.to_string());
        svg.push_str("\" y1=\"");
        svg.push_str(&y1.to_string());
        svg.push_str("\" x2=\"");
        svg.push_str(&x2.to_string());
        svg.push_str("\" y2=\"");
        svg.push_str(&y2.to_string());
        svg.push_str("\"><title>");
        svg.push_str(&html_escape_text(json_str_or_empty(edge, "kind")));
        svg.push_str("</title></line>");
    }
    for node in nodes {
        let id = json_u64_field(node, "id");
        let Some((x, y)) = positions.get(&id) else {
            continue;
        };
        let kind = json_str_or_empty(node, "kind");
        let name = json_str_or_empty(node, "name");
        let color = project_graph_view_color(kind);
        svg.push_str("<g><circle cx=\"");
        svg.push_str(&x.to_string());
        svg.push_str("\" cy=\"");
        svg.push_str(&y.to_string());
        svg.push_str("\" r=\"15\" fill=\"");
        svg.push_str(color);
        svg.push_str("\"/><text class=\"node-label\" x=\"");
        svg.push_str(&(x + 24).to_string());
        svg.push_str("\" y=\"");
        svg.push_str(&(y - 2).to_string());
        svg.push_str("\">");
        svg.push_str(&html_escape_text(name));
        svg.push_str("</text><text class=\"node-kind\" x=\"");
        svg.push_str(&(x + 24).to_string());
        svg.push_str("\" y=\"");
        svg.push_str(&(y + 13).to_string());
        svg.push_str("\">");
        svg.push_str(&html_escape_text(kind));
        svg.push_str(" #");
        svg.push_str(&id.to_string());
        svg.push_str("</text></g>");
    }
    svg.push_str("</svg>");
    svg
}

fn project_graph_view_x(kind: &str) -> i64 {
    match kind {
        "file" => 70,
        "import" => 210,
        "struct" | "enum" | "type_alias" | "function" | "define" => 390,
        "domain" => 590,
        _ => 760,
    }
}

fn project_graph_view_color(kind: &str) -> &'static str {
    match kind {
        "file" => "#2563eb",
        "import" => "#0f766e",
        "struct" | "enum" | "type_alias" => "#7c3aed",
        "function" | "define" => "#c2410c",
        "domain" => "#be123c",
        _ => "#525252",
    }
}
